### ISSUE TITLE
DecodingError で止まりました

### ISSUE THREAD

**Issue by tenzyu** [chun37/spotify-to-discord#4]
```py
[INFO][2021-03-05 19:02:24,591] main:100: added "アゲハ蝶" from DAISUKEDCC
[INFO][2021-03-05 19:02:24,929] main:107: deleted "アゲハ蝶" from DAISUKEDCC
[INFO][2021-03-05 19:04:26,742] main:100: added "アゲハ蝶" from DAISUKEDCC
[INFO][2021-03-05 19:04:27,044] main:107: deleted "アゲハ蝶" from DAISUKEDCC
[INFO][2021-03-05 19:05:28,139] main:100: added "アゲハ蝶" from DAISUKEDCC
Traceback (most recent call last):
  File "/home/tenzyu/spotify-to-discord/main.py", line 127, in <module>
    s.start()
  File "/home/tenzyu/spotify-to-discord/main.py", line 107, in start
    logger.info('deleted "%s" from %s', track.name, user.display_name)
AttributeError: 'DecodingError' object has no attribute 'name'
```

**Comment by chun37** [comment]
track に name が無いなんてあるのか！？

**Comment by chun37** [comment]
@tenzyu 
再現性がありませんでした。
ログに出力する値を変更したので、更新して再実行してください><
それでエラーが再度出るようだったら、アクション(add, remove)と 曲ID を載せて issue 立ててください。

**Comment by chun37** [comment]
#5 で対応
